name: Rust Format Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt -- --check