name: Rust Format Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find crate directory
        id: find-crate
        run: |
          echo "CRATE_DIR=$(find . -name Cargo.toml -exec dirname {} \; | head -n 1)" >> $GITHUB_ENV

      - name: Run cargo fmt
        run: cargo fmt -- --check
        working-directory: ${{ env.CRATE_DIR }}